_commit: v1.12.1-6-gbf0c0a5
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: false
homepageEnabled: false
ingress: false
labels: 'app: homepage'
name: homepage
namespace: homepage
pvc: false
reloader: true
resources:
- configmaps.yaml
- deployments.yaml
- external-secrets.yaml
- ingresses.yaml
- rbac.yaml
- secrets.yaml
- service-accounts.yaml
- services.yaml
service: false
serviceAccount: false
upstreamURL: https://gethomepage.dev/
url: https://github.com/charlesthomas/homelab-homepage
