---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bookmarks
  namespace: homepage
spec:
  target:
    name: bookmarks
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        bookmarks.yaml: |-
          {{ .bookmarks }}
  data:
    - secretKey: bookmarks
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: homepage-bookmarks
        metadataPolicy: None
